In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,3,5],
                 [3,6,4],
                 [4,5,2]])
arr2 = np.array([[1,5,5],
                 [5,3,7],
                 [4,5,6]])
arr3 = np.array([[1,3,5,6],
                 [3,6,4,5],
                 [4,5,2,3]])

In [5]:
arr1 + arr2

array([[ 2,  8, 10],
       [ 8,  9, 11],
       [ 8, 10,  8]])

In [6]:
arr1 * arr2

array([[ 1, 15, 25],
       [15, 18, 28],
       [16, 25, 12]])

In [7]:
arr1.dot(arr2)

array([[36, 39, 56],
       [49, 53, 81],
       [37, 45, 67]])

In [8]:
arr2.dot(arr1)

array([[36, 58, 35],
       [42, 68, 51],
       [43, 72, 52]])

In [10]:
arr = np.array([2,6,4,5,7])

In [11]:
arr[:2]

array([2, 6])

In [15]:
arr1

array([[1, 3, 5],
       [3, 6, 4],
       [4, 5, 2]])

In [14]:
arr1[ :,1:2]

array([[3],
       [6],
       [5]])

In [17]:
arr1[1:2,1:2]

array([[6]])

In [18]:
arr1[1:,1:]

array([[6, 4],
       [5, 2]])