In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])

In [4]:
arr + 1

array([2, 3, 4, 5, 6, 7, 8])

In [7]:
print(arr +1)
print(arr -1)
print(arr *2)
print(arr /2)
print(arr **2)

[2 3 4 5 6 7 8]
[0 1 2 3 4 5 6]
[ 2  4  6  8 10 12 14]
[0.5 1.  1.5 2.  2.5 3.  3.5]
[ 1  4  9 16 25 36 49]


In [8]:
arr *= 2

In [9]:
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [11]:
print(arr.max())
print(arr.min())

14
2


In [13]:
arr = np.array([[1,2,3],
               [2,4,5],
               [3,5,7]])

In [14]:
arr.max(axis =0) #column wise max

array([3, 5, 7])

In [15]:
arr.min(axis=1) #row wise min

array([1, 2, 3])

In [17]:
arr.sum()

np.int64(32)