In [1]:
import numpy as np

In [2]:
arr = np.array([2,5,3,4,6,4,5,12])

In [3]:
arr

array([ 2,  5,  3,  4,  6,  4,  5, 12])

In [4]:
arr[5]

np.int64(4)

In [6]:
arr[4:]

array([ 6,  4,  5, 12])

In [8]:
arr[:3]

array([2, 5, 3])

In [5]:
arr[2:5]

array([3, 4, 6])

In [10]:
arr = np.array([[2,4,5,6],[4,3,5,7],[5,3,4,8]])

In [11]:
arr

array([[2, 4, 5, 6],
       [4, 3, 5, 7],
       [5, 3, 4, 8]])

In [19]:
arr[2,3]

np.int64(8)

In [12]:
arr[ : , 1:2]

array([[4],
       [3],
       [3]])

In [14]:
arr[1:2,:3]

array([[4, 3, 5]])

In [17]:
arr[1:,2:]

array([[5, 7],
       [4, 8]])