In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,4,23,5],[4,5,3,8]])
arr2 = np.array([[2,5,4,3],[4,6,3,5]])

In [4]:
arr1,arr2

(array([[ 1,  4, 23,  5],
        [ 4,  5,  3,  8]]),
 array([[2, 5, 4, 3],
        [4, 6, 3, 5]]))

In [8]:
np.vstack((arr2,arr1))

array([[ 2,  5,  4,  3],
       [ 4,  6,  3,  5],
       [ 1,  4, 23,  5],
       [ 4,  5,  3,  8]])

In [9]:
np.hstack((arr1,arr2))

array([[ 1,  4, 23,  5,  2,  5,  4,  3],
       [ 4,  5,  3,  8,  4,  6,  3,  5]])

In [13]:
arr3 =np.concatenate((arr1,arr2),axis=0)

In [14]:
arr3

array([[ 1,  4, 23,  5],
       [ 4,  5,  3,  8],
       [ 2,  5,  4,  3],
       [ 4,  6,  3,  5]])

In [20]:
np.hsplit(arr3,4)

[array([[1],
        [4],
        [2],
        [4]]),
 array([[4],
        [5],
        [5],
        [6]]),
 array([[23],
        [ 3],
        [ 4],
        [ 3]]),
 array([[5],
        [8],
        [3],
        [5]])]

In [19]:
np.vsplit(arr3,2)

[array([[ 1,  4, 23,  5],
        [ 4,  5,  3,  8]]),
 array([[2, 5, 4, 3],
        [4, 6, 3, 5]])]