In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [7]:
q = 0

for i in lst:
  if (i > 5):
    print(i)
    q += 1
print(q)

6
7
8
9
10
5


In [5]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
lst > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [10]:
print(len(lst[lst > 5]))

5


In [11]:
print(lst[lst % 3 == 0])
print(len(lst[lst % 3 == 0]))

[3 6 9]
3
