In [11]:
!pip install numpy

In [12]:
import numpy as np

In [13]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [14]:
lst = [[1,2,3],[3,45,67]]

In [15]:
type(lst)

list

In [16]:
arr = np.array(lst)

In [17]:
arr

array([[ 1,  2,  3],
       [ 3, 45, 67]])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim

2

In [20]:
arr.shape

(2, 3)

In [22]:
arr.size

6

In [23]:
arr.dtype

dtype('int64')

In [24]:
zeros = np.zeros((3,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
ones = np.ones((4,4))

In [27]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])