In [1]:
import numpy as np

In [19]:
arr = np.random.random((4,3))

In [5]:
np.random.random()

0.18790020534024154

In [13]:
if np.random.random() > 0.5:
  print("correct")
else:
  print("wrong")

correct


In [15]:
np.arange(1,10,3)

array([1, 4, 7])

In [18]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [20]:
arr

array([[0.1762239 , 0.94568537, 0.79448532],
       [0.12030214, 0.81197815, 0.58173881],
       [0.29522197, 0.46815658, 0.89816807],
       [0.70151817, 0.57469818, 0.57258648]])

In [21]:
np.reshape(arr,(3,4))

array([[0.1762239 , 0.94568537, 0.79448532, 0.12030214],
       [0.81197815, 0.58173881, 0.29522197, 0.46815658],
       [0.89816807, 0.70151817, 0.57469818, 0.57258648]])

In [22]:
arr.flatten()

array([0.1762239 , 0.94568537, 0.79448532, 0.12030214, 0.81197815,
       0.58173881, 0.29522197, 0.46815658, 0.89816807, 0.70151817,
       0.57469818, 0.57258648])