In [1]:
import numpy as np

In [3]:
arr = np.array([[2,3,45,32,56],[5,7,2,4,8],[6,3,2,8,9]])

In [4]:
arr

array([[ 2,  3, 45, 32, 56],
       [ 5,  7,  2,  4,  8],
       [ 6,  3,  2,  8,  9]])

In [12]:
np.sort(arr, axis =1, kind ='margesort')

array([[ 2,  3, 32, 45, 56],
       [ 2,  4,  5,  7,  8],
       [ 2,  3,  6,  8,  9]])

In [ ]:
arr2 = np.sort(arr, axis =1, kind ='margesort')

In [16]:
np.sort(arr2, axis =0,kind='stable')

array([[ 2,  3,  5,  7,  8],
       [ 2,  3,  6,  8,  9],
       [ 2,  4, 32, 45, 56]])